### ISSUE TITLE
Error 500 on 404 pages

### ISSUE THREAD

**Issue by hieuh25** [tradingstrategy-ai/frontend#100]
Website returns error 500 in case it should return 404, example: https://tradingstrategy.ai/trading-view/ethereum/sushiswap

**Comment by kenkunz** [comment]
The cause of the `500` errors was a change in the SvelteKit `load` function API.

Previous: returning `undefined` indicated a failed match for the layout or page route (i.e., `404`).

Updated: must explicitly return a `{ status, error }` object to indicate `404`
