### ISSUE TITLE
Move prettier to its own Github workflow

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#114]
- Currently it is being embedded with Cypress checks
- For the readability of the PR and errors, this should be spun out to its own Github workflow file, so it will get an independent green check mark

**Comment by kenkunz** [comment]
Totally agree – was originally planning to break it out this way, but I realized it would likely conflict with other commits on #58 (Containerize frontend). Was still hoping to get back to that one to close it out soon (blocked by #94). Will plan to address this after that.

**Comment by kenkunz** [comment]
fixed by #58
