### ISSUE TITLE
Headings with links

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#123]
Our trading pair pages has h1 headings with links. The new theme probably needs some brainstorming work how these should be presented.

Links can be also removed.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/49922/175280678-91532fc3-76b7-42db-b842-7acce3e83978.png">

**Comment by kenkunz** [comment]
@allozaur let me know your opinion on this when you have a moment.

Here's an example pair page:
https://tradingstrategy.ai/trading-view/binance/pancakeswap-v2/jst-bnb-2

**Comment by kenkunz** [comment]
Links were removed when the pairs page was updated to Theme 0.1 design
