### ISSUE TITLE
More white space on blog pages

### ISSUE THREAD

**Issue by tsorro** [tradingstrategy-ai/frontend#124]
Can we add a bit of white space between the title + date section and the article? It doesn't have to be much, just 0.5 - 1 body text lines. At the moment it looks a bit crammed/tight

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/20061308/175295619-a68163b3-0b18-4025-b181-c54113c7acbd.png">

**Comment by kenkunz** [comment]
Thanks for reporting, @tsorro.

This is done (was a quick & easy change) – not deployed yet, will go live with the next `frontend` deploy.

FYI, this is still the old blog post layout. Now that we have the new theme colors / fonts live, we will be working to implement the rest of the new design system. We should be making serious headway on this next week. I know you've reviewed this before … but here's a screenshot of the new blog post layout.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/35901/175402871-1b930a2c-cecd-4b04-b9ea-7e214b215b45.png">

**Comment by tsorro** [comment]
Sounds great, thank you Ken.
