### ISSUE TITLE
Gracefully handle delays and errors when loading data table date

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#17]
e.g. on page 

https://tradingstrategy.ai/trading-view/ethereum/tokens/0xee4833ba7409711a6400f78300632717993ae9ef

Because the token is currently untracked, the backend API gives an error. However this error displayed as `alert()`, in very unfriendly and unprofessional manner.

https://tradingstrategy.ai/trading-view/ethereum/tokens/0xee4833ba7409711a6400f78300632717993ae9ef

The actual error is

`Backend error: 422 {'json_body': {'error_id': 'LookupInputException', 'message': "Trading pairs for tokens ['0xee4833ba7409711a6400f78300632717993ae9ef'] exist, but do not have tracked data. See https://tradingstrategy.ai/docs/programming/tracking.html for more details."}}`

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/49922/157613295-aac67ac0-bbdc-4e81-b3ae-6677df3c0461.png">

**Comment by servatj** [comment]
If we handle this I think we can return an empty result and show the standard message no data is available. Will this be enough ? Or do we have to show an specific message for untracked data ? 

![image](https://user-images.githubusercontent.com/3521485/158553370-115eecf3-41c7-47e9-bbb7-6e653c424918.png)

**Comment by miohtama** [comment]
New idea: can you change it to show that it directly shows the error message from the server. Then I will change the backend error message to something user friendly.
