### ISSUE TITLE
Fix incosistent blog titles with CSS (style all titles always using title case)

### ISSUE THREAD

**Issue by tsorro** [tradingstrategy-ai/frontend#172]
Blog post titles have inconsistent use of capital letters, which gets highlighted on our newsletters especially as the titles are near each other. 

---> Please fix the inconsistent titles with CSS to style all titles using title case always. 

Example from a draft newsletter 
![Image](https://user-images.githubusercontent.com/20061308/185381254-c344c26e-69d7-4cae-8762-c2bda1ed2a7d.png)

**Comment by kenkunz** [comment]
@tsorro, @miohtama, @TradingStrategyLawrence 

I just want to confirm that we're OK with the results of using CSS `text-transform: capitalize` as a solution for this.

The CSS solution doesn't implement true [Title Case](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) (which leaves certain words lowercased). Rather, **I**t **C**apitalizes **T**he **F**irst **L**etter **O**f **E**very **W**ord **I**ndiscriminately. This include short connector words ("a", "the", "and", etc.) as well as words that would typically be lowercase ("vs") – which we tend to use a lot in our titles. The preview image below shows how this looks for all our blog titles.

The other (minor) downside to the CSS approach is that the blog titles in our RSS feed and social meta tags will not reflect the same case.

If this is not desired… I see two alternatives for fixing this:
1. **quick-n-dirty:** Someone manually fixes all the titles in Ghost. Perhaps we hire an intern for this? (If we do… can I have them bring me coffee?).
   - pros: quick, no dev cost, consistent title everywhere using proper case
   - cons: one-time manual effort, not future-proof (people need to remember to use proper case when composing blog articles)
2. **JS solution:** There are some JS libraries that do this for you. We can pick the "best" one and 
   - pros: no manual effort needed, consistent title everywhere using proper case, future-proof
   - cons: dev effort (small but not trivial)

**Preview of titles using CSS solution**

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/35901/185421878-1e5d5656-ada9-4476-94d2-d1e2cb0cc6cd.png">
