### ISSUE TITLE
Clear all filters UX tweaking

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#19]
When none of the filters are selected, the default "Clear all filters" button is confusing

<img width="316" alt="image" src="https://user-images.githubusercontent.com/49922/157933836-625e6647-70b4-4762-a3e5-a1d719476c1b.png">

User (me) tries to press it.

This is because it is not obvious it is greyed out button. I suggest hiding it altogether when no filters are selected or change it to label "Select filters:"  that then will change to "Clear filters" button if any of the filters are selected. Something along this lines.

**Comment by kenkunz** [comment]
Makes sense. I lean towards your second suggestion (mutating label) – will experiment a bit.
