### ISSUE TITLE
Dealing with multichain exchanges on advanced search page

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#20]
Currently, Sushiswap is deployed across different chains. Thus, you will get duplicate entries in the advanced search UI.

We need to somehow separate these entries. 

<img width="261" alt="image" src="https://user-images.githubusercontent.com/49922/158349415-16649f4d-29f1-4012-9644-6344683e1f6e.png">

Try search with term "sushi".

**Comment by kenkunz** [comment]
I looked into this.

It appears that SushiSwap is labeled differently on Ethereum ("Sushiswap") vs. the other chains ("SushiSwap"). See below.

The facet-based _filtering_ is case-_insensitive_, but the facet _counts_ are case-_sensitive_.

Is it possible to normalize this label on the backend?

<img src="https://user-images.githubusercontent.com/35901/158473725-01329ae5-56c6-456c-8aff-63ad0d74514f.jpg" alt="sushiswap exchanges" width="624">

**Comment by kenkunz** [comment]
This was fixed server-side (consistent Exchange name across chains)
