### ISSUE TITLE
Aave: Add Reserves tile to Trading Data summary page

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#212]
**Epic:** tradingstrategy-ai/oracle#116
**Depends on:** #211

# Goal

Include a new **Lending Reserves** content tile (with appropriate icon and description) on **Trading data » Explore data** section, with target URL: `/trading-view/reserves`

**Comment by allozaur** [comment]
![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/b6b7379b-b9d7-42db-b63a-f613a3152943)

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/d5b9c093-3bdc-4c29-a4cb-1b250c97dab2)
