### ISSUE TITLE
Open Positions index page

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#235]
This issue is part of **Epic #231**

# Goal

Update `/strategy/[strategy_id]/open-positions` page to reflect the new [Design System 0.2 figma design spec](https://www.figma.com/file/OxDd6gslnRMW9p5DEZzlqI/TRADE-Design-System-v0.2?node-id=1397%3A49150).

![image](https://user-images.githubusercontent.com/35901/201782121-d09a52af-a365-4b6e-98a4-778f8268ea2a.png)

**Comment by miohtama** [comment]
One functional change:

- We need column that's "Remarks" 
- Something special about positions 
- Let's have it on left
- It will be "SL" = (stop loss) if the position was closed for stop loss
- It will be "TEST"  the position was for testing
