### ISSUE TITLE
Jarring user experience for viewing different trading pairs of a particular exchange

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/frontend#239]
Example: navigate to https://tradingstrategy.ai/trading-view/binance/pancakeswap-v2

Scroll down to the table, every time you click 'next', you are taken to the top of the page to see the same information about pancakeswap, then if you want to click 'next' again, you have to scroll down to the bottom of the page again. 

It would be nice if it didn't move navigation every time 'next' was clicked. And/or have some left and right arrows at the top of the table could also be nice.

Also, pressing the back button takes one completely out of this page, instead of going to the previous navigation in the table.

**Comment by kenkunz** [comment]
Thanks for reporting this, @AlexTheLion123.

I've noticed this as well and also found it quite jarring. Unfortunately, this may be impossible to fix until we move away from the legacy (jQuery-based) [DataTables](https://datatables.net/) library that is used for rendering most of our data tables.

There are other issues as well, including CLS (cumulative layout shift) issues that affect our Google Search rankings. The code is also quite difficult to debug and maintain (the imperative style of jQuery libraries is generally a poor fit for declarative frameworks like Svelte).

I've brought up DataTables concerns a few times – @miohtama has indicated that it is not likely to be a priority this year, but perhaps something we could address early in 2023.

**Comment by kenkunz** [comment]
These issues were fixed when we migrated to the new datatables implementation.
