### ISSUE TITLE
Display highest volume/liquidity on first click

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/frontend#245]
As an example, navigate to [https://tradingstrategy.ai/trading-view/avalanche/trader-joe](https://tradingstrategy.ai/trading-view/avalanche/trader-joe), and click back and forth between volume and liquidity on the trading pairs table. To me, it would make sense for to display highest volume and highest liquidity trading pairs on the first click, not lowest. Zero volume/liquidity trading pairs are unlikely to be of interest to most traders. Consider also displaying biggest gainers on first click of price as well, instead of biggest losers, but volume and liquidity seem to be more relevant.

**Comment by kenkunz** [comment]
This was fixed when we migrated to new datatables implementation.
