### ISSUE TITLE
small data table issues

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/frontend#251]
Yesterday, I was working with the pair data tables and identified some things that could improve user experience. 

- Control + click on row opens new link instead of same page
- Remember sorting preferences e.g. Highest liquidity first 
- If row is clicked and then website navigates to pair info page, remember which page of the table the user was on so that when back button is clicked, user to taken back to same page 
- Also related to #245

**Comment by kenkunz** [comment]
All of these issues were fixed when we migrated to the new datatables implementation.
