### ISSUE TITLE
Add explainer video to homepage and about us page

### ISSUE THREAD

**Issue by TradingStrategyLawrence** [tradingstrategy-ai/frontend#280]
Hi @kenkunz,

I have a quick small request here. Could we please embed this video (https://youtu.be/iPXuqwYDv9U) on the homepage and on the about us page.

Here are a couple of screenshots where we would like them placed.

![Screenshot 2022-12-15 at 1 28 00 pm](https://user-images.githubusercontent.com/105222542/207871281-30e2702a-bad9-43d6-b0f7-cd92aa4bd8e0.png)

![Screenshot 2022-12-15 at 1 28 49 pm](https://user-images.githubusercontent.com/105222542/207871290-645846b5-1903-442a-94bd-0a7bf620804a.png)

Let me know if you have any questions regarding this.

Thanks,
Lawrence

**Comment by kenkunz** [comment]
@TradingStrategyLawrence FYI – we discussed this at design-sync today – per Mikko & Teemu's direction, we're removing it from the front page for now (keeping it on About page). We'll add video back to the front page when we have a new shorter video that's better for that context.
