### ISSUE TITLE
Display a warning on trading pair page if it's listed on a blacklisted exchange

### ISSUE THREAD

**Issue by plamut** [tradingstrategy-ai/frontend#288]
Background: https://github.com/tradingstrategy-ai/oracle/pull/214#issuecomment-1359056234

Some of the exchanges are marked as `"uniswap_v2_incompatible"`, and pairs listed on them should be marked clearly on the pair page. The `/pairs` endpoint returns a list of `PairSummary` objects, which now contain `exchange_type` info (the API spec will be updated soon).

If `exchange_type` is `"uniswap_v2_incompatible"` a warning should be rendered on such pair's page.

**Comment by kenkunz** [comment]
@plamut I reviewed tradingstrategy-ai/oracle#176 and tradingstrategy-ai/oracle#214.

Two questions and a comment…

### 1. `oracle` deployment timing?

From what I can tell, the `oracle` changes are not yet live. Is that correct? E.g., the `exchange_type` for the [BUSD-USDT](https://tradingstrategy.ai/trading-view/binance/nomiswap-stable/busd-usdt) pair is still `uniswap_v2` (based on the `api/pair-details` endpoint).

Expected timeframe for deployment?

### 2. update exchange details in addition to pair details?

Do we also need to display a warning on the [exchange details page for Nomiswap Stable](https://tradingstrategy.ai/trading-view/binance/nomiswap-stable)?

If _yes_ … it a safe assumption that the `exchange_type` value on the `/api/exchange-details` endpoint will also be equal to `uniswap_v2_incompatible` (for this exchange)?

### 3. design considerations

As a general design principle, _business logic_ belongs on the backend and _display logic_ on the frontend.

Adding special-case display logic based on a specific value of `exchange_type` feels more like _business logic_ that should reside on the backend. We already have some special-case logic to display a warning if `liquidity` is below a certain threshold (except in the special-special-case where the `exchange_type` is Uniswap v3). Proliferating these types of decisions to the `frontend` feels fragile and unscalable.

One alternative approach would be to add a `quality_warnings` array field (or something similar) to each entity (exchanges, tokens, pairs, etc.). For every item in this array, we could display a warning on the appropriate `frontend` page. If the value is `[]` or `null`, we assume the entity is "healthy".

Any thoughts on this?

**Comment by kenkunz** [comment]
This is currently blocked by: tradingstrategy-ai/backend#95

**Comment by plamut** [comment]
Should be unblocked now, that issue has now been resolved.
