### ISSUE TITLE
Add blockchain to Trading pair listing table

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#346]
Because Uniswap v3 is deployed on multiple chains and cannot be currently differentiated in the listing.

Add new column `Blockchain`

![image](https://user-images.githubusercontent.com/49922/218744123-a3cf1e18-0be7-4702-891f-6acddbddbc49.png)

https://tradingstrategy.ai/trading-view/trading-pairs

**Comment by kenkunz** [comment]
this was addressed by #575
