### ISSUE TITLE
Strategy index/details labels for assets under management (AUM)

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#348]
# Goal

Use consistent labeling for **Assets under management** / **AUM** on [Strategy index](https://tradingstrategy.ai/strategies) and [Strategy overview](https://tradingstrategy.ai/strategies/pancake-eth-usd-sma) pages.

## Details
- current label on index view is "Amount of assets" – change to "AUM" with title/hover of "Assets under management"
- current label on details view is "Value in trading positions" – change to "Assets under management"

**Comment by kenkunz** [comment]
@miohtama:

## Questions

1. verify formula – is this correct?
2. is this what is already shown as "Value in trading positions" on strategy overview?
   - the value displayed is `portfolioStats.total_equity` (where `portfolioStats` is based on [`getPortfolioLatestStats`](https://github.com/tradingstrategy-ai/trade-executor-frontend/blob/master/src/lib/state/stats.ts#L30-L38))
   - keep this value and update the label to TVL / Total Value Locked?
3. should we also update the label on [Strategy index](https://tradingstrategy.ai/strategies) from "Amount of assets" to "Total value locked" for consistency?

**Comment by AlexTheLion123** [comment]
@kenkunz We decided to just go with the standard definition for TVL and also have the strategy performance on the same chart e.g. https://app.enzyme.finance/vault/0x1b83ba4527c837d462d5b78d65a097dabae5ea89 here you can toggle the chart between share price and assets under management, we would have them on the same chart.

Seems like the term we are using is `assets under management`

**Comment by AlexTheLion123** [comment]
I think it would be the `Value in trading positions`. Just clarfying, is `cash` included in this figure?

**Comment by kenkunz** [comment]
## Discussion at 01.03.2023 meeting

Term we are aligning on: Assets under management

Abbreviation: AUM
- Alternatively, just "Assets" where we need a shorter label.

In Crypto world, "TVL" – doesn't communicate well to non-crypto world.
