### ISSUE TITLE
Strategy positions index - sort by date descending

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#351]
# Goal

When clicking on Open positions or Closed positions tabs under a strategy, the positions should be sorted date descending (most recent at the top) by default.

**Comment by kenkunz** [comment]
@AlexTheLion123 / @miohtama 

Depending on the positions index page (opened / closed / frozen) different date columns are included (`opened_at` / `closed_at` / `frozen_at`).

We could sort by the date column that is shown on each positions index, or we could always use **ID** descending (which should correspond 1:1 to `opened_at`).

Using **ID** everywhere is probably simpler, but the other option is not very difficult either.

What is your preference?

**Comment by AlexTheLion123** [comment]
@kenkunz  Probably ID, do you agree @miohtama ?
