### ISSUE TITLE
Strategy index 500 error

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#393]
# Issue

The strategy index page `/strategies` is currently returning a `500` error.

## Details

Initial investigation showed that the `pancake-eth-usd-sma` strategy was the source of the error. This strategy was temporarily removed from the configured strategies in production.

Determine what is causing an error with this strategy. This is likely due to some data that `frontend` expects but it not fully populated in the returned API data for `pancake-eth-usd-sma`. The `frontend` code should be resilient incomplete data. If needed, a separate issue should be opened on [trade-executor](https://github.com/tradingstrategy-ai/trade-executor) to address the data issue.

**Comment by kenkunz** [comment]
## Causes

- the `pancake-eth-usd-sma` strategy does not currently have any chart data – the payload returned from `metadata` has an empty array for `summary_statistics.performance_chart_90_days`
- the `frontend` code for determining the X-axis range for the strategy thumbnail charts was not resilient to this scenario

## Fixes

- [x] opened tradingstrategy-ai/trade-executor#250
- [x] made `frontend` code resilient to this scenario

**Comment by miohtama** [comment]
I think we have this situation after the trade executor boots up. The 90 days datais generated server-side and keep in-memory store. It is not generated immediately so there might be a time period when `metadata` is not yet fully populated.

**Comment by miohtama** [comment]
It's only per rebalance, so for this particular strategy 3-4 times a day. Because it's cron'ed

**Comment by miohtama** [comment]
Can you open a trade executor ticket to "Populate all metadata on startup"

**Comment by kenkunz** [comment]
> Can you open a trade executor ticket to "Populate all metadata on startup"

Done: https://github.com/tradingstrategy-ai/trade-executor/issues/251
