### ISSUE TITLE
Link to token pages from trading pair pages

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#40]
Add links to the token pages from trading pair pages

- Summary (symbol)
- Body text 
- We no longer need to display the token address on the body text as now this information is available on the token page

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/49922/158816688-15a8b39e-e323-442b-abcd-2254a03912c4.png">

**Comment by kenkunz** [comment]
This appears to have been implemented a long time ago.
