### ISSUE TITLE
Home Hero Highlights improvements

### ISSUE THREAD

**Issue by TradingStrategyLawrence** [tradingstrategy-ai/frontend#403]
Hi @kenkunz,

Can we update the homepage to include the following text "Access of developer sophisticated algorithmic trading strategies for DeFi" underneath the main header "Next generation algorithmic trading protocol for decentralised markets".

![Screenshot 2023-03-24 at 2 07 20 pm](https://user-images.githubusercontent.com/105222542/227546233-b01fbc00-4e85-4798-ad94-f5e767132990.png)

Discussed on Discord here: https://discord.com/channels/888448459168948284/966616449311465504/1088826534506278942

Here is a small mock of what we are looking for. If you are able to make it uniform and look right that would be appreciated.

![Screenshot 2023-03-24 at 2 25 22 pm](https://user-images.githubusercontent.com/105222542/227554265-79e06495-59c1-4e64-b989-7c81dc62a1da.png)

Let me know if you have any issues with this.

Thanks,
Lawrence

**Comment by allozaur** [comment]
@TradingStrategyLawrence i will take over this one ;)
