### ISSUE TITLE
Token block explorer links

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#41]
Token pages should have a link (button) to the corresponding blockchain explorer, similar to trading pair pages have.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/49922/158816975-cae13e94-4981-46fa-81f0-9e063b88c7e5.png">

- Spec changes needed? The backend has a function [ChainId.get_address_link()](https://github.com/tradingstrategy-ai/client/blob/master/tradingstrategy/chain.py#L114) to produce the links

- Minor UI design needed (how/where to display button) - tagging @kenkunz

**Comment by kenkunz** [comment]
This appears to have been implemented a while ago.
