### ISSUE TITLE
Wallet integration – deposit tokens to strategy vault

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#426]
# Goal

An **investor** should be able to deposit tokens to a particular strategy vault from the **deposit wizard payment** step.

**Comment by kenkunz** [comment]
See [Discord thread](https://discord.com/channels/888448459168948284/1108512393639772231). Per @miohtama: 

1. Need to get this code to the frontend: [ReceiveWithAuthorization](https://github.com/Polymarket/relayer-deposits/blob/6eb0af88ad3af8af31499b87e8f6eb53ab1a9546/packages/sdk/src/utils/receiveSignature.ts#L39)
2. Need to get ERC3009 ABI file
3. Need to get ABI for this contract ([Enzyme USDC payment forwarder](https://github.com/tradingstrategy-ai/web3-ethereum-defi/blob/master/contracts/in-house/src/VaultUSDCPaymentForwarder.sol))
4. Here is the Python logic how to put together a transaction: [transfer_with_authorization.py](https://github.com/tradingstrategy-ai/web3-ethereum-defi/blob/master/eth_defi/usdc/transfer_with_authorization.py)
5. Here is an example test case: [test_enzyme_usdc_payment_forwarder.py](https://github.com/tradingstrategy-ai/web3-ethereum-defi/blob/master/tests/enzyme/test_enzyme_usdc_payment_forwarder.py)

**Comment by kenkunz** [comment]
Also see [this thread](https://discord.com/channels/888448459168948284/1110286030730448966):

Smart contract deployed: [0xe3eaaba28b03d873304958eb30f412b6ccd4016c](https://polygonscan.com/address/0xe3eaaba28b03d873304958eb30f412b6ccd4016c#writeContract)

**Comment by kenkunz** [comment]
@miohtama I am running into a couple issues submitting a `buySharesOnBehalf` transaction…

I generated the following ERC-3009 typed payload:

<details>
<summary>View payload</summary>

```json
{
    "types": {
        "ReceiveWithAuthorization": [
            {
                "name": "from",
                "type": "address"
            },
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "value",
                "type": "uint256"
            },
            {
                "name": "validAfter",
                "type": "uint256"
            },
            {
                "name": "validBefore",
                "type": "uint256"
            },
            {
                "name": "nonce",
                "type": "bytes32"
            }
        ],
        "EIP712Domain": [
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "version",
                "type": "string"
            },
            {
                "name": "chainId",
                "type": "uint256"
            },
            {
                "name": "verifyingContract",
                "type": "address"
            }
        ]
    },
    "domain": {
        "name": "USD Coin (PoS)",
        "version": "2",
        "chainId": "137",
        "verifyingContract": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"
    },
    "primaryType": "ReceiveWithAuthorization",
    "message": {
        "from": "0xefd90a79fee79aba176a7e1b0e101193fb7d7bda",
        "to": "0xe3eaaba28b03d873304958eb30f412b6ccd4016c",
        "value": "2000000",
        "validAfter": "0",
        "validBefore": "1685431815",
        "nonce": "0x1ea28df486d695e42afb632510ab422b51ecee53d0f327f1931de670d384ae18"
    }
}
```
</details>

…which was then signed by my the wallet, generating the following signature:

<details>
<summary>View signature</summary>

```
0xf620e659605111291090009b7afb75f3c4b38f32873c3f1e9903c1f99bbe104679bc6b8aff05b92746e847d632677171cd0bf4b6af7386a859ea70ca9d8d105e1b
v: 27
s: 0xf620e659605111291090009b7afb75f3c4b38f32873c3f1e9903c1f99bbe1046
r: 0x79bc6b8aff05b92746e847d632677171cd0bf4b6af7386a859ea70ca9d8d105e
```
</details>

…which was then used to compose the following transaction signature:

<details>
<summary>View transaction signature</summary>

```javascript
prepareWriteContract({
	address: vault_usdc_payment_forwarder,
	abi: vaultUsdcPaymentForwarderABI,
	functionName: 'buySharesOnBehalf',
	args: [
		"0xEFD90a79feE79aba176A7E1B0E101193fb7d7bda",
		"0xe3eaaba28b03d873304958eb30f412b6ccd4016c",
		2000000,
		0,
		1685431815,
		"0x6b03f192cb171a704071981ddb5379fcd26a8c030e1a9b184f3ea644d68197b4",
		27,
		"0xf620e659605111291090009b7afb75f3c4b38f32873c3f1e9903c1f99bbe1046",
		"0x79bc6b8aff05b92746e847d632677171cd0bf4b6af7386a859ea70ca9d8d105e",
		1
	]
});

```
</details>

When trying to submit this transaction, I receive the following error:

<details>
<summary>View error details</summary>

```
MetaMask - RPC Error: Internal JSON-RPC error. {
	code: -32603,
	message: 'Internal JSON-RPC error.',
	data: {code: -32000, message: 'execution reverted'}
}

REJECTED: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xEFD90a79feE79aba176A7E1B0E101193fb7d7bda","to":"0xE3eAabA28B03d873304958EB30f412b6CCd4016c","data":"0xb5b0ab32000000000000000000000000efd90a79fee79aba176a7e1b0e101193fb7d7bda000000000000000000000000e3eaaba28b03d873304958eb30f412b6ccd4016c00000000000000000000000000000000000000000000000000000000001e84800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006475ac1881302135a13de8aae5a35dd97a643ab048424b34125b61e192a91e7d26fb6aec000000000000000000000000000000000000000000000000000000000000001c659e2e33ff84c340836fba8c3c956d4248cfe2b99950be0cc2fa2af5a22da6110459797bbcedee154b99405bf5ad1459673e05e0635e9c11f65bf6bca30a47b20000000000000000000000000000000000000000000000000000000000000001","accessList":null}
```
</details>

I attempted to submit the transaction with a specified `gasPrice` and `gasLimit` – in this case the request initiated the wallet approval step and (after approving) was submitted to the blockchain. However, the transaction failed. Unfortunately, the transaction details / logs don't give me too much to go on.
https://polygonscan.com/tx/0x641d1c2e6d2d78b91a4a095f3ccabb4f258ac45e306820e82825209084cb26ac

Any thoughts on what is going wrong here, or what I should try next to troubleshoot / diagnose?

**Comment by miohtama** [comment]
It means something goes wrong - and probably the signature is somehow calculated incorrectly.

We can figure out this by forcing MetaMas to send the transaction. Then we can open the tx in a transaction debugger like Tenderly.io to see the actual revert message or failing call.
