### ISSUE TITLE
Add client-side fillter for high/low values

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#443]
We are currently having some spikes (real spikes, but should not affect the charts).

- We need to filter these out
- This can be done by postprocessing the data on the client side before rendering
- It can be done with a simple clip rule if `high > close * x pct then set high = close * pct`
- Same for low

<img width="1656" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/49922/76af1b0d-719d-42e9-bf37-78ffa708989c">

**Comment by kenkunz** [comment]
Additional requirements per Discord discussion:

- clip percents should be runtime configuration variables
- should be a tuple (low_clip_pct, high_clip_pct)
- default values `0.66` (low `33%` below close), `1.33` (high `33%` above close)
