### ISSUE TITLE
Add blockchain to Trading pair list

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#444]
Because it is now Uniswap v3 all over the place without difference.

<img width="1750" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/49922/5abe96f0-4bf7-4668-a96e-888f400ebcd8">

https://tradingstrategy.ai/trading-view/trading-pairs

**Comment by kenkunz** [comment]
Duplicate of #346
