### ISSUE TITLE
Investor wizard UAT: Add "max" control to MoneyInput component

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#480]
# Issue

It is difficult for an investor to invest all of their USDC or redeem all of their shares. We can make this much easier with a "max" control that auto-populates the `MoneyInput` value with the max available.

This is related to #480, but different (that ticket is a validation constraint this one is a control to auto-populate).

## Feedback

Per @kenkunz

> **[purchase wizard]** I would like to have an easy way to deposit ALL of my available USDC into a strategy.
>
> ---
>
> **[redeem wizard]** My "Number of shares" balance was 9.83 SLS1. I input this amount in order to redeem my full balance. This resulted in an error in the UI: "Error: Redemption confirmation from wallet account failed." I can see from console error the additional detail "burn amount exceeds balance". This is due to rounding where the actual amount of shares I have is 9.826677069842125.

Per @TradingStrategyLawrence 
> I started to go through the deposit and redeem wizard, but encountered some issues. I have recorded a [video](https://www.loom.com/share/7b5b089cab27497f86df64d8372f6174) to illustrate them. I am unable to redeem and also the wallet connectivity seems to be an issue. As you can see I have to “restart” the wizard to try to go through to fix it

**Comment by allozaur** [comment]
@kenkunz @miohtama 

I improved the Money Input's UI/UX like this:

> Note: The dropdown indicator on USDC is not to be yet implemented. This is just a visual suggestion of how we could handle switching tokens on deposit payments,

### Deposit

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/b52f7f8e-8277-4002-8c68-3e2aad3d712d)

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/fe07f8dd-642b-41c3-b4a4-02f0bc6576f5)

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/317a2b1f-58d3-48f2-92b7-deb5dd3f8bf1)

### Redeem


![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/53651d1e-cac1-4e60-8a13-96e164a73035)


![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/e57f46cb-6fa5-4b86-bf0a-c44b471948e6)

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/7a961989-f356-4d25-9548-5caebf96cf1a)

**Comment by kenkunz** [comment]
@allozaur my 2¢ – this feels like a lot to cram into the input control.

Exploring a few alternatives… thoughts?

| # | Desktop | Mobile |
| --- | --- | --- |
| **1.** | <img width="693" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/bcd7e7a3-0e6d-4e2f-9a7b-ccb7d8ea9e9c"> | <img width="399" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/80a4885f-7994-4343-984a-564494c01329"> |
| **2.** | <img width="707" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/90b6bce6-734e-44e8-8de8-ba90baa6ff42"> | <img width="400" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/0c51b292-1cd4-409f-aed2-de0b189daa52"> |
| **3.** | <img width="711" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/e268751f-9fd1-44db-900b-2fcb96d7fb5f"> | <img width="401" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/92bb4dec-0a8a-4c71-8719-8ecb67679f46"> |
| **4.** | <img width="713" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/69489f4d-2e46-454a-9a2a-2aacb0c12f9e"> | <img width="401" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/b8e52052-bfad-4cef-9a93-4b4873a06583"> |
| **5.** | <img width="712" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/3285bc39-cb0f-4fcb-8907-ce3f0519d3d7"> | <img width="399" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/7ea30854-88d0-4f37-aae2-ea0bc22829ad"> |

**Comment by allozaur** [comment]
@kenkunz i think that these propositions feel less intuitive in comparison to the general UI patterns in DeFi apps such as Uniswap, dHedge, QuickSwap etc..

I think that this type of input works best and it is really a simple and intuitive UI:

https://github.com/tradingstrategy-ai/frontend/assets/37627284/8e627ae3-35c6-469c-ab5a-187a0bbb8397

https://github.com/tradingstrategy-ai/frontend/assets/37627284/ece7aae2-78c4-4ca1-805e-7ba26439d725

The balance amount is featured as a primary UI having large size on `Deposit status` step where it should be highlighted alongside the USDC value of shares:

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/bf59afc4-f887-48d1-b039-e082bc221931)

But then when user wants to decide how much they want to redeem, simplifying it to this UI and properly balancing the sizing of the input and balance numbers and also the MAX button works very well and utilises very few UI elements in an elegant manner:

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/6a2d18f2-eefe-484c-8527-0271e8d69c21)

**Comment by kenkunz** [comment]
@allozaur thanks for the additional insights on this.

I see your point in relation to comparisons with Uniswap and other exchanges / dapps. I am curious to hear @miohtama's thoughts on this. Some of his previous design direction in relation to the investor wizards has been to _differentiate_ from the typical dapp designs, since they can be intimidating to people who are newer to the space.

One thing that stands out to me about Uniswap and other exchange implementations is the **vertical alignment** of the **numeric input value** and the **token symbol** – which indicates the relationship between those elements. In the design concepts above, the numeric input is center-aligned, so it feels less obvious to me that it's related to the `SLS1` symbol.

If we are trying to model our design on the patterns in other exchanges / dapps, I wonder if we want to go further and use this common pattern for showing the result of the transaction in another (with indication that its an estimate):

<img width="620" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/13deac50-12f4-4212-b215-80c54c9b7191">

**Comment by allozaur** [comment]
@kenkunz yeah, that's a good idea in my opinion
