### ISSUE TITLE
Strategy index tile enhancements

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#488]
# Goal

Improve appearance and usability of strategy index tiles.

## Details

- [x] entire tile should be clickable (vs. just "View strategy" button)
- [x] ensure the tile layout looks correct across viewport widths
- [x] add strategy icon as shown in pitch deck mock up below

> **Note** adding a "mountain" gradient to chart (similar to Performance tab) is out of scope of this ticket – see #489)

## Mock up from pitch deck

![image](https://github.com/tradingstrategy-ai/frontend/assets/35901/9672af64-d608-4cc4-aa7e-826215a12dac)

**Comment by allozaur** [comment]
## Desktop

### Vertical layout

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/51396e81-ac86-454f-b722-0d793ec85bb8)

### Horizontal layout


![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/fe19509f-1065-4434-af44-1a09ba034654)


## Mobile

![Image](https://github.com/tradingstrategy-ai/frontend/assets/37627284/1c39cc3b-788a-4efc-af8c-8af594b93248)
