### ISSUE TITLE
Responsive Navbar Not Working.

### ISSUE THREAD

**Issue by prajapatiomkar** [tradingstrategy-ai/frontend#560]
## In mobile device side bar not showing properly.
![image](https://github.com/tradingstrategy-ai/frontend/assets/72141037/f73f38c6-b902-4a57-a19b-311548b7bb0d)

**Comment by kenkunz** [comment]
@prajapatiomkar thanks for reporting this! I will take a look and hopefully have a fix live shortly.

**Comment by kenkunz** [comment]
@prajapatiomkar FYI fix has been deployed. Thanks again for reporting.

-Ken

**Comment by prajapatiomkar** [comment]
Now, Its working fine Great Work Ken :)
