### ISSUE TITLE
Upgrade to node 16.x / npm 8.x

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#59]
The current deployment target for `frontend` is `node v14` / `npm v6`.

This is outdated – `node v16` / `npm v8` became the Active LTS on `2021-10-26`.

`node v16` includes many important updates, including:
* `V8` upgrade to `v9` (performance improvements)
* `es2021` features (new String & Promise methods; logical assignment)
* native Apple Silicon support

`npm v8` includes substantial upgrades in dependency management and performance over `v6` (changes `package-lock.json` to `lockfileVersion=2`).

This is a low-risk upgrade. It will improve developer efficiency and decrease merge conflicts resulting from incompatible `lockfileVersion=1` commits.

**Comment by miohtama** [comment]
`trade-executor-frontend` library depends on Node v16, as it is using one very handy v16 only function. `Array.at(-1)` to get the last item of the array.

So might need to upgrade sooner than later, as I need to bring the library to the main site.

**Comment by hieuh25** [comment]
For simplicity I usually do both specifying `engines.node` and adding `,nvmrc` with same version in the repo. Yes it's a bit strict and limited but we will have consistency :D
