### ISSUE TITLE
Search navigation issue

### ISSUE THREAD

**Issue by hieuh25** [tradingstrategy-ai/frontend#60]
How to reproduce:
1. go to any token pair page, for example https://tradingstrategy.ai/trading-view/ethereum/sushi/eth-wbtc
2. enter another pair into the search box in the page header, for example: bnb usdc
3. the page content changes except the chart content https://tradingstrategy.ai/trading-view/binance/pancakeswap-v2/bnb-usdc

**Comment by kenkunz** [comment]
This was fixed by #77. Tested on ✅ Chrome, ✅ Firefox, ✅ Brave.
