### ISSUE TITLE
Update token search results to include liquidity and volume stats

### ISSUE THREAD

**Issue by plamut** [tradingstrategy-ai/frontend#63]
https://github.com/tradingstrategy-ai/backend/pull/26 added two new fields to token info returned by the `/tokens` and `/token/details` API endpoints, namely `liquidity_latest` and `volume_24h` (both in USD). Token search results should reflect this.

**Comment by miohtama** [comment]
@kenkunz Bumping on this one - probably already done?

**Comment by kenkunz** [comment]
I somehow missed this ticket in the backlog / never responded…

The **search results** automagically already include the liquidity and volume metrics – once these fields were added to the Typesense export in `oracle` and the data made its way to the search index, `frontend` showed them in the search results.

To call this truly _done_ I think we should add these metics to the **token details** page. This is trivial task – will prioritize and try to fit it in this week.

**Comment by kenkunz** [comment]
I also looked at the **token index** page – both fields are already included, but `liquidity_latest` has an inaccurate column header "Liq 24h" – should be fixed.
