### ISSUE TITLE
Trading entity page refresh (part 1)

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#636]
# Goal

As an investor, I want various trading entity pages (chains, exchanges, tokens, pairs, lending reserves) to be up to date with the most relevant and useful information, so that I can effectively research and analyze trading opportunities.

## Tickets

> [!NOTE]
> Oracle/backend tickets, as well as frontend tickets with backend dependencies, have been de-scoped to #784

### Frontend tickets

- [x] #640 
- [x] #641 
- [x] #642 
- [x] #776
- [x] #643
- [x] #781

## Additional requirements

To be added to above tickets and/or broken out as separate tickets:

- Terminology: Swap fee -> trading fee
   - already added this to trading pair page ticket
   - also need to address on advanced search page
- Make sure all new pages are in sitemap, like lending reserves
- Make sure breadcrumbs get Google breadcrumbs treatment
- When we use wrapped token display Quote token as ETH (WETH), some change across all pages
- Make use trading pairs and tokens are searchable with both ETH and WETH

**Comment by miohtama** [comment]
Very good

Some more changes

- Terminology: Swap fee -> trading fee
- Make sure all new pages are in sitemap, like lending reserves
- Make sure breadcrumbs get Google breadcrumbs treatment
- Interest rate: make Available in several different time formats and have "Funding rate" table. Common are 8h and 1y, but there might be more. Benchmark with "Funding rate comparison" services.
