### ISSUE TITLE
Trade-executor tags

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#649]
Trade-executor can have tags that indicate about it 's context

- Prototype version
- Alpha version
- Beta version
- Internal testing

Tags are not mutually exclusive.

- Tags should be displayed in the strategy tiles
- Tags should be displayed in the strategy landing page title

Special tags rules:

- Sort order on the strategy tiles: Beta > Alpha > Prototype > Internal testing
- Internal testing: Do not display risk metrics. Have a disclaimer: "This strategy is only for internal trading data recording and is not intended to make profit."

Tags can be read in `metadata.tags` and it is a list of strings.

**Comment by miohtama** [comment]
First new metadata variable needed.

**Comment by kenkunz** [comment]
@miohtama currently the only tag that is assigned to a strategy is the `live` tag on `test-strategy-1`

I'm guessing we don't want to display the `live` tag, correct? We could change the "live" logic to instead tag non-live strategies as `test` or `Internal test` (and remove the `live` tag). Or… we could special-case the `live` tag in frontend to not display that one. Thoughts?

FYI, here's the UI to display something like a "Beta" tag on index view and strategy title:

<img src="https://github.com/tradingstrategy-ai/frontend/assets/35901/e63e5048-e051-4542-8bd1-befed812b744">
<img src="https://github.com/tradingstrategy-ai/frontend/assets/35901/3c1842ce-d358-4d2a-b9b3-dce7601ba5ef"></td>

**Comment by kenkunz** [comment]
> @miohtama currently the only tag that is assigned to a strategy is the `live` tag on `test-strategy-1`
> 
> I'm guessing we don't want to display the `live` tag, correct? We could change the "live" logic to instead tag non-live strategies as `test` or `Internal test` (and remove the `live` tag). Or… we could special-case the `live` tag in frontend to not display that one. Thoughts?

**Rethinking this…**

I see we have both `badges` and `tags` props on the strategy metadata. So I'm thinking `badges` is what we want to display as a badge in the UI, whereas `tags` can be used for other purposes (e.g., how we're currently using `live` tag for filtering).

**So as I see it…**
- no need for any change in how we're using `live` tag
- `badges` (instead of `tags`) will be displayed as badge in UI

**Make sense?**

**Comment by kenkunz** [comment]
Per discussion with @miohtama at backlog review meeting:

- special-case for `live` tag – only display this when user has admin role (for public users, _all_ strategies that are displayed are `live`, so no need for the tag). Badge color should be green.
- sort order described above should be handled in the backend Python code, not `frontend`
