### ISSUE TITLE
Inconsistent strategy performance metrics

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#654]
# Issue

The strategy _overview_  and _performance_ pages display inconsistent performance metrics.

## Details

Per @tsorro on [discord](https://discord.com/channels/888448459168948284/966616449311465504/1194233386466811914):
> We have broken profitability calculations with the Multipair breakout strategy on Uniswap v3
https://tradingstrategy.ai/strategies/enzyme-polygon-multipair
> - Overview page is showing 8.2% profit
> - Performance page is showing -7.3% profit
> <img src="https://github.com/tradingstrategy-ai/frontend/assets/35901/1493a22b-5ab8-4c67-9dd2-9a2dc50c7cb4" height="250" float="left">
> <img src="https://github.com/tradingstrategy-ai/frontend/assets/35901/37802a7a-5823-4c1d-b9ba-d07ec4ec4cfa" height="250">

## Frontend analysis

These metrics are different for _all_ strategies, not just for *Multipair breakout*:

<table>
<thead>
<tr>
<th align="left">Strategy</th>
<th>Overview page</th>
<th>Performance page</th>
</tr>
</thead>
<tbody>
<tr>
<td>ETH-USD breakout on Uniswap v3</td>
<td align="right">1.1%</td>
<td align="right">0.8%</td>
</tr>
<tr>
<td>MATIC-USD breakout on Uniswap v3</td>
<td align="right">7.2%</td>
<td align="right">7.6%</td>
</tr>
<tr>
<td>ETH-USD long strength on Uniswap v3</td>
<td align="right">15.4%</td>
<td align="right">15.2%</td>
</tr>
<tr>
<td>Multipair breakout strategy on Uniswap v3</td>
<td align="right">8.2%</td>
<td align="right">-7.3%</td>
</tr>
<tr>
<td>Open-ended momentum strategy for Polygon</td>
<td align="right" valign="top">-0.4%<br/><sub>*backtested</sub></td>
<td align="right" valign="top">-9.2%</td>
</tr>
<tr>
<td>ETH mean reversion bounce</td>
<td align="right" valign="top">24.7%<br/><sub>*backtested</sub></td>
<td align="right" valign="top">4.4%</td>
</tr>
</tbody>
</table>

Both of these values come from `metadata` endpoint:
- Overview page "Performance" is from: `summary_statistics.key_metrics.profitability`
- Performance page "Lifetime return" is from: `summary_statistics.return_all_time`

I also noticed that these pages display different values for _trade period_:
- Overview page "Age" is from `metadata` endpoint: `summary_statistics.key_metrics.started_at`
- Performance page "Trade period" is from `state` endpoint: `stats.portfolio[-1].summary.duration`

> [!Note]
> We are in the process of updating the Performance page to utilize stats from `long_short_table` instead of the properties listed above. This data is not yet available for all strategies, and is some cases is based on backtested data as the source. See #357, tradingstrategy-ai/trade-executor#706

#### 1. Why are the _performance_ values different? 

What is the underling difference in the definition / calculation for `summary_statistics.key_metrics.profitability` vs. `summary_statistics.return_all_time`?

&nbsp;&nbsp;&nbsp;&nbsp;**1.b.** should `summary_statistics.return_all_time` be deprecated / removed?
&nbsp;&nbsp;&nbsp;&nbsp;(only currently used on the Performance page)

#### 2. Why are the _age_ / _trade period_ values different? 

What is the underling difference in the definition / calculation for `metadata:summary_statistics.key_metrics.started_at` vs. `state:stats.portfolio[-1].summary.duration`?

&nbsp;&nbsp;&nbsp;&nbsp;**2.b.** should `stats.portfolio[-1].summary` trade stats be deprecated?
&nbsp;&nbsp;&nbsp;&nbsp;(only currently used on the Performance page)

#### 3. What is the desired change to the Performance page?

<table>
<tr>
<th>Option&nbsp;1</th>
<td>
Replace <code>summary_statistics.return_all_time</code> on the Performance page with <code>summary_statistics.key_metrics.profitability</code> (and similarly with the age / trade period metrics).
</td>
</tr>
<tr>
<th>Option&nbsp;2</th>
<td>
Wait until #357 is done (per note above) and see if the new <code>long_short_table</code> stats addresses this issue. (This requires the <code>long_short_table</code> stats to be available on all strategies).
</td>
</tr>
<tr>
<th>Option&nbsp;3</th>
<td>other?</td>
</tr>
</table>

**Comment by kenkunz** [comment]
@AlexTheLion123 when you have a few minutes can you look at questions 1 and 2 above?

**Comment by kenkunz** [comment]
@miohtama, @tsorro – see question 3 above – what is your preferred solution? (answer may depend on answers to questions 1, 2).

**Comment by tsorro** [comment]
> @miohtama, @tsorro – see question 3 above – what is your preferred solution? (answer may depend on answers to questions 1, 2).

Teemu: I would expect to see lifetime returns on the overview page and in the highlighted data slot on the Performance tab as well

**Comment by kenkunz** [comment]
> Teemu: I would expect to see lifetime returns on the overview page and in the highlighted data slot on the Performance tab as well

Thanks, @tsorro.

I believe both of these values are *meant* to reflect lifetime returns (based on the tooltip for Profitability – it shows the full strategy timeframe as its "calculation period"). Will wait to hear what @alexth_ finds in terms of how the two values are calculated differently.

**Comment by AlexTheLion123** [comment]
> > Teemu: I would expect to see lifetime returns on the overview page and in the highlighted data slot on the Performance tab as well
> 
> Thanks, @tsorro.
> 
> I believe both of these values are _meant_ to reflect lifetime returns (based on the tooltip for Profitability – it shows the full strategy timeframe as its "calculation period"). Will wait to hear what @alexth_ finds in terms of how the two values are calculated differently.

Have identified the source of the error and created P0 [ticket](https://github.com/tradingstrategy-ai/trade-executor/issues/747). Seems like  `summary_statistics.return_all_time` is the correct value which is the value on the performance page.

**Comment by AlexTheLion123** [comment]
@kenkunz @tsorro @miohtama Can confirm the error here is due to resampling. 

`summary_statistics.key_metrics.profitability` defaults to resampling to a daily time period which loses data points when there are multiple positions in a day.

`summary_statistics.return_all_time` does not resample and appears to be the correct value, which is unfortunate in this case as it is the worse value. 

Have opened P0 ticket on tradeexecutor to address this.
