### ISSUE TITLE
live stats performance page

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/frontend#673]
### Summary

- Currently, the performance page defaults to showing live statistics on the performance page. [Example](https://tradingstrategy.ai/strategies/polygon-eth-spot-short/performance)
- Since these live stats are calculated in the exact same way that the backtested stats are calculated, some of the stats will be incorrect. At a glance, `Return %` and `Annualised return %` are clearly erroneous. However, this can be corrected on the trade executor side by https://github.com/tradingstrategy-ai/trade-executor/pull/777
- Also, some stats are unmeaninful e.g. `Cash at start`

### Acceptance criteria

- [x] Hide `Cash at start`

**Comment by AlexTheLion123** [comment]
@kenkunz The `Return %` and `Annualised return %` should be fixed and can be shown for both live and backtested strategies

**Comment by AlexTheLion123** [comment]
@kenkunz `Return %` and `Annualised Return %` have now been corrected and can be shown again @kenkunz.

Also, cash at start can be hidden for live stats

**Comment by miohtama** [comment]
@AlexTheLion123 Can you ticket this you?

**Comment by miohtama** [comment]
@AlexTheLion123 Double check the trade stats that it is not correct
