### ISSUE TITLE
Inconsistent position data

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#674]
# Issue

@tsorro noted a discrepancy in data between the position index and position details pages. See [discord thread](https://discord.com/channels/888448459168948284/1202955006253342820).

## Details

<table>
<tr>
<th></th>
<th>
<a href="https://tradingstrategy.ai/strategies/enzyme-polygon-multipair/closed-positions">Index page</a>
</th>
<th>
<a href="https://tradingstrategy.ai/strategies/enzyme-polygon-multipair/closed-positions/158">Details page</a>
</th>
</tr>
<th align="left">Screenshot</th>
<td>
<img src="https://github.com/tradingstrategy-ai/frontend/assets/35901/15edef77-2696-4601-a1a9-7b9c062f8d47">
</td>
<td>
<img src="https://github.com/tradingstrategy-ai/frontend/assets/35901/f1760a26-98f3-4476-afba-90e8e273ddc6">
</td>
<tr>
</tr>
<tr>
<th align="left">Profitability</th>
<td><code>0.7%</code></td>
<td><code>0.1%</code></td>
</tr>
<tr>
<th align="left">Value</th>
<td>---</td>
<td><code>$214.11</code></td>
</tr>
<tr>
<th colspan="3">After some time…</th>
</tr>
<tr>
<th align="left">Profitability</th>
<td>formatted: <code>0.1%</code><br>original: <code>0.0014009103641000615</code></td>
<td>formatted: <code>0.1%</code><br>original: <code>0.0014009103641000617</code></td>
</tr>
<tr>
<th align="left">Value</th>
<td><code>$214.02</code></td>
<td><code>$214.11</code></td>
</tr>
<tr>
<tr>
<th colspan="3">Data sources</th>
</tr>
<tr>
<th align="left">Profitability</th>
<td valign="top"><code>stats.positions[position_id].at(-1).profitability</code></td>
<td>
  <code>positionInfo.realisedProfitability</code><br>
  <b>Formula:</b><br>
  ((last trade <code>executed_price</code>) - (first trade <code>executed_price</code>)) / (first trade <code>executed_price</code>)
</td>
</tr>
<tr>
<th align="left">Value</th>
<td valign="top"><code>stats.closed_positions[position_id].value_at_open</code></td>
<td>
  <code>positionInfo.valueAtOpen</code><br>
  <b>Formula:</b><br>
  (first trade <code>executed_quantity</code>) * (first trade <code>executed_price</code>)
</td>
</tr>
</table>

@miohtama indicated that it is likely better to use the values from `stats` as the latency should be relatively low and the value is probably more accurate / correct.

**Comment by AlexTheLion123** [comment]
@kenthropic Yes it seems like `stats.positions` on trade executor is more robust since it can account for:
- repaired/failed positions
- interest claimed/repaid
- multiple buys/sells
