### ISSUE TITLE
Standardize code formatting

### ISSUE THREAD

**Issue by servatj** [tradingstrategy-ai/frontend#68]
## Goals
* standardize the code style conventions used in `frontend`
* keep it consistent with other Trading Strategy Svelte projects (e.g., `trade-executor-frontend`, `design-system`
* follow conventions that are standard in the Svelte / SvelteKit community (easier to introduce new developers with Svelte experience)
* automate it some developers don't need to think about it

**Comment by kenkunz** [comment]
Our other Svelte projects are all using `prettier` with the standard `.prettierrc` configuration that ships with SvelteKit:
```json
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100
}
```

I have to admit… `tabs` was an adjustment for me, but I've grown to like it. Also this:

<a target="_blank" href="https://youtu.be/SsoOG6ZeyUI">
<img src="https://user-images.githubusercontent.com/35901/170368836-79d1e1de-a125-47fa-9853-e369700a7e80.png" alt="image" width="370" height="202">
<div><b>Tabs versus Spaces</b></div>
</a>
