### ISSUE TITLE
Add strategy fee info

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#686]
# Goal

As an investor, I want to know the fees associated with a strategy as I research options and make a deposit, so that I have greater transparency and insight about expected returns.

## Details

The following fee information should be added as a strategy sub-page and a deposit wizard step:
- Management fee: 0%
- Performance fee: 0%
- Trading Strategy Protocol Fee: 0%
- Enzyme Protocol Fee: 0.1% (if Enzyme vault)

Also add a label "During the beta Trading Strategy does not charge any fees".

## Design consideration

Does this require a separate page, or can the fee data be integrated into an existing page (both for strategy and deposit wizard)?

## Acceptance Criteria

1. A user viewing strategy details can easily locate and view fee info
   - enzyme protocol fee is included if the strategy has enzyme vault
2. A user making a deposit is shown the fee info in the deposit wizard
   - we only support deposits for strategies with enzyme vault, so enzyme protocol fee is included
3. All fee values may be hard-coded for now. In the future they will likely come from the strategy configuration and/or a smart contract.

**Comment by miohtama** [comment]
@AlexTheLion123 Let's open a ticket to pull out the fee into trade-executor

**Comment by miohtama** [comment]
Enzyme fee is unlikely to change any time soon, so let's just use a hardcoded value in the UI for now.
