### ISSUE TITLE
Alert message overflow issue

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#705]
# Issue

Alert dialog message has overflow problem when it includes very long unbroken words. For example, when completing a deposit and there's an unexpected error when calling a very long ABI function name.

<table>
<tr>
<td>
<img width="797" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/81610cc3-601d-4dda-8509-8e1a425eebbf">
</td>
<td>
<img width="392" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/35901/0c9f58d5-5b95-4c48-857a-433f5b6e292d">
</td>
</tr>
</table>

**Comment by miohtama** [comment]
We have pinned down this issue to be an issue with Keystone hardware wallet

- Rabbit with Keystone does not work
- Rabby without Keystone works
- Ledger works

I have contacted Keystone representative what is the best way to resolve the issue with them.
