### ISSUE TITLE
getaddrinfo: EAI_AGAIN again crashes the server-side rendering process

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#82]
SvelteKit has [an internal fetch hook](https://github.com/tradingstrategy-ai/frontend/blob/master/src/hooks/index.ts) that goes directly to the backend IP address, bypassing the public Internet.

It should be enabled, but I am seeing this in logs.

```
FetchError: request to https://tradingstrategy.ai/api/candles?pair_id=1656735&time_bucket=4h failed, reason: getaddrinfo EAI_AGAIN tradingstrategy.ai
    at ClientRequest.<anonymous> (file:///root/frontend/build/shims-eb608bdd.js:6246:11)
    at ClientRequest.emit (node:events:526:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  erroredSysCall: 'getaddrinfo'
````

Investigate why it tries to go through the public Internet. Might be SvelteKit version issue after upgrade.

**Comment by kenkunz** [comment]
The `externalFetch` hook is only used for requests that happen in `load` function:
https://kit.svelte.dev/docs/hooks#externalfetch

We are calling `/api/candles` in the normal <script> context of the pair details:
https://github.com/tradingstrategy-ai/frontend/blob/18dc03c1a12038197e2291dc9b69da88ebee7e36/src/routes/trading-view/%5Bchain%5D/%5Bexchange%5D/%5Bpair%5D/index.svelte#L246

This will get called during SSR when the page is initially rendering (then it will get called again client-side). We do not need candle data on the server side, and it is discarded / re-fetched client-side.

**Short-term fix:** ensure that the `reloadCandlesOnBucketChange` function is only called client-side.

**Long-term fix:** ensure that the new ChartIQ charts implementation only requests the candle / liquidity data client-side.

**Comment by miohtama** [comment]
Managed to also capture this unrelated error:

```
FetchError: request to http://127.0.0.1:3456/top-momentum failed, reason: socket hang up
    at ClientRequest.<anonymous> (file:///root/frontend/build/shims-eb608bdd.js:6246:11)
    at ClientRequest.emit (node:events:526:28)
    at Socket.socketOnEnd (node:_http_client:466:9)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
````

But we will also need to investigate what causes "socket hang up" on backend.

**Comment by kenkunz** [comment]
Did a little more research on this. It seems that `getaddrinfo ENOTFOUND` causes a particularly fatal, unrecoverable error. I tried rolling back to an earlier version of `frontend` (before recent SvelteKit upgrades) and it's no better.

When `fetch` encounters this error server-side (in `load` function or in main `<script>` code), the `node` process dies. Surprisingly, wrapping `fetch` in `try / catch` doesn't solve the issue 😱 

Assuming any such errors are intermittent, I would suggest wrapping the `node` server command on prod in some type of simple supervisor script that auto-restarts on-exit.

**Comment by miohtama** [comment]
> Assuming any such errors are intermittent, I would suggest wrapping the node server command on prod in some type of simple supervisor script that auto-restarts on-exit.

@hieuh25 @servatj does the frontend container have an autorestart (attempts)? Might consider moving to this over the weekend.

**Comment by hieuh25** [comment]
> > Assuming any such errors are intermittent, I would suggest wrapping the node server command on prod in some type of simple supervisor script that auto-restarts on-exit.
> 
> @hieuh25 @servatj does the frontend container have an autorestart (attempts)? Might consider moving to this over the weekend.

Kinda, since the simplest way to serve the container is to use `docker run` (last step in the deployment at #58), you can combine it with a [restart policy](https://docs.docker.com/engine/reference/run/#restart-policies---restart).
For example to autorestart with 3 retries after failure, the run command can be: `docker run -dp TARGET_PORT:3000 --env-file=MYENVFILE --restart=on-failure:3 ghcr.io/tradingstrategy-ai/frontend:<VERSION>`
