### ISSUE TITLE
Chart rendering problem 

### ISSUE THREAD

**Issue by hieuh25** [tradingstrategy-ai/frontend#96]
Steps to reproduce:
* Go to: https://tradingstrategy.ai/trading-view/binance/pancakeswap-v2/titano-bnb#1h
* Check the chart, for me it shows only 1 candle
![image](https://user-images.githubusercontent.com/1258431/168287641-1f42424c-de50-476e-a401-a57cada9276c.png)

There seem to be 2 problems which go hand in hand:
* The chart shows only 1 candle, zoom or scroll _might_ fix it
* Open the network tab and you can see it's spamming the same API endpoint over and over again, this might be even more pressing matter than the UI one

**Comment by kenkunz** [comment]
The single candle correctly represents the trade data for this trading pair (based on our APIs).

The spamming of our endpoint is clearly an issue, though.

ChartIQ's logic for determining when to ask for more data is less sophisticated than I realized. If it requests data for a given timeframe and that data includes significant gaps, it will keep re-requesting data for the same timeframe.

Was able to fix this by following the first approach outlined here:
https://documentation.chartiq.com/tutorial-DataIntegrationQuoteFeeds.html#toc6__anchor

Also improved the heuristic for deciding when "no more historical data available" (compare to first trade date), and set a limit on max ticks to request.
