### ISSUE TITLE
Negative price issue on BNB-USDT

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#98]
Investigate. Likely bad raw data from Uniswap:

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/49922/169254230-3a21096e-0070-4f06-bd26-beab7db57f21.png">

https://tradingstrategy.ai/trading-view/binance/pancakeswap-v2/bnb-usdt

**Comment by kenkunz** [comment]
This was fixed on the backend.
